package restaurantsearch;
// Generated Feb 23, 2017 8:41:59 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Guest generated by hbm2java
 */
public class Guest  implements java.io.Serializable {


     private Integer guestId;
     private String guestEmail;
     private Set<Reservation> reservations = new HashSet<Reservation>(0);

    public Guest() {
    }

	
    public Guest(String guestEmail) {
        this.guestEmail = guestEmail;
    }
    public Guest(String guestEmail, Set<Reservation> reservations) {
       this.guestEmail = guestEmail;
       this.reservations = reservations;
    }
   
    public Integer getGuestId() {
        return this.guestId;
    }
    
    public void setGuestId(Integer guestId) {
        this.guestId = guestId;
    }
    public String getGuestEmail() {
        return this.guestEmail;
    }
    
    public void setGuestEmail(String guestEmail) {
        this.guestEmail = guestEmail;
    }
    public Set<Reservation> getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set<Reservation> reservations) {
        this.reservations = reservations;
    }




}


