package restaurantsearch;
// Generated Feb 23, 2017 8:41:59 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private Integer locationId;
     private String locationName;
     private String keyWord;
     private Set<Restaurant> restaurants = new HashSet<Restaurant>(0);

    public Location() {
    }

    public String getKeyWord() {
        return keyWord;
    }

    public void setKeyWord(String keyWord) {
        this.keyWord = keyWord;
    }

	
    public Location(String locationName) {
        this.locationName = locationName;
    }
    public Location(String locationName, Set<Restaurant> restaurants) {
       this.locationName = locationName;
       this.restaurants = restaurants;
    }
   
    public Integer getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }
    public String getLocationName() {
        return this.locationName;
    }
    
    public void setLocationName(String locationName) {
        this.locationName = locationName;
    }
    public Set<Restaurant> getRestaurants() {
        return this.restaurants;
    }
    
    public void setRestaurants(Set<Restaurant> restaurants) {
        this.restaurants = restaurants;
    }




}


