package restaurantsearch;
// Generated Feb 23, 2017 8:41:59 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reservation generated by hbm2java
 */
public class Reservation  implements java.io.Serializable {


     private Integer reservationId;
     private Restaurant restaurant;
     private User user;
     private Date reservationDate;
     private String reservationTime;
     private int reservationNumGuests;
     private Set<Guest> guests = new HashSet<Guest>(0);

    public Reservation() {
    }

	
    public Reservation(Restaurant restaurant, User user, Date reservationDate, String reservationTime, int reservationNumGuests) {
        this.restaurant = restaurant;
        this.user = user;
        this.reservationDate = reservationDate;
        this.reservationTime = reservationTime;
        this.reservationNumGuests = reservationNumGuests;
    }
    public Reservation(Restaurant restaurant, User user, Date reservationDate, String reservationTime, int reservationNumGuests, Set<Guest> guests) {
       this.restaurant = restaurant;
       this.user = user;
       this.reservationDate = reservationDate;
       this.reservationTime = reservationTime;
       this.reservationNumGuests = reservationNumGuests;
       this.guests = guests;
    }
   
    public Integer getReservationId() {
        return this.reservationId;
    }
    
    public void setReservationId(Integer reservationId) {
        this.reservationId = reservationId;
    }
    public Restaurant getRestaurant() {
        return this.restaurant;
    }
    
    public void setRestaurant(Restaurant restaurant) {
        this.restaurant = restaurant;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getReservationDate() {
        return this.reservationDate;
    }
    
    public void setReservationDate(Date reservationDate) {
        this.reservationDate = reservationDate;
    }
    public String getReservationTime() {
        return this.reservationTime;
    }
    
    public void setReservationTime(String reservationTime) {
        this.reservationTime = reservationTime;
    }
    public int getReservationNumGuests() {
        return this.reservationNumGuests;
    }
    
    public void setReservationNumGuests(int reservationNumGuests) {
        this.reservationNumGuests = reservationNumGuests;
    }
    public Set<Guest> getGuests() {
        return this.guests;
    }
    
    public void setGuests(Set<Guest> guests) {
        this.guests = guests;
    }

    int setReservationId() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


