package restaurantsearch;
// Generated Feb 23, 2017 8:41:59 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private String userFname;
     private String userLname;
     private String userPhone;
     private String userEmail;
     private Set<Reservation> reservations = new HashSet<Reservation>(0);

    public User() {
    }

	
    public User(String userFname, String userLname, String userPhone, String userEmail) {
        this.userFname = userFname;
        this.userLname = userLname;
        this.userPhone = userPhone;
        this.userEmail = userEmail;
    }
    public User(String userFname, String userLname, String userPhone, String userEmail, Set<Reservation> reservations) {
       this.userFname = userFname;
       this.userLname = userLname;
       this.userPhone = userPhone;
       this.userEmail = userEmail;
       this.reservations = reservations;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUserFname() {
        return this.userFname;
    }
    
    public void setUserFname(String userFname) {
        this.userFname = userFname;
    }
    public String getUserLname() {
        return this.userLname;
    }
    
    public void setUserLname(String userLname) {
        this.userLname = userLname;
    }
    public String getUserPhone() {
        return this.userPhone;
    }
    
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public Set<Reservation> getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set<Reservation> reservations) {
        this.reservations = reservations;
    }




}


